var graph = {
  "nodes":[
    {
      "id":"2962",
      "labels":[
        "Class",
        "VFB",
        "_Class",
        "Anatomy",
        "Entity"
      ],
      "properties":{
        "iri":"http://purl.obolibrary.org/obo/FBbt_00007060",
        "in_subset":[
          "larval_OF"
        ],
        "annotation-id":[
          "FBbt:00007060"
        ],
        "has_children":true,
        "ontology_prefix":"VFB",
        "description":[
          "A structure consisting of multiple cell components but which is not itself a cell and does not have (complete) cells as a part."
        ],
        "annotation-has_obo_namespace":[
          "fly_anatomy.ontology"
        ],
        "label":"multi-cell-component structure",
        "is_defining_ontology":false,
        "is_root":false,
        "is_obsolete":false,
        "ontology_name":"vfb",
        "short_form":"FBbt_00007060",
        "ontology_iri":"http://purl.obolibrary.org/obo/fbbt/vfb/vfb.owl",
        "obo_id":"FBbt:00007060",
        "obo_xref":[
          "{\"database\":\"CARO\",\"id\":\"0001000\",\"description\":null,\"url\":null}"
        ],
        "annotation-database_cross_reference":[
          "CARO:0001000"
        ],
        "obo_definition_citation":[
          "{\"definition\":\"A structure consisting of multiple cell components but which is not itself a cell and does not have (complete) cells as a part.\",\"oboXrefs\":[{\"database\":\"FBC\",\"id\":\"DOS\",\"description\":null,\"url\":null}]}"
        ],
        "olsId":"vfb:http://purl.obolibrary.org/obo/FBbt_00007060"
      }
    },
    {
      "id":"148",
      "labels":[
        "Class",
        "VFB",
        "_Class",
        "Root",
        "Entity"
      ],
      "properties":{
        "iri":"http://www.w3.org/2002/07/owl#Thing",
        "ontology_name":"vfb",
        "has_children":false,
        "ontology_prefix":"VFB",
        "short_form":"Thing",
        "ontology_iri":"http://purl.obolibrary.org/obo/fbbt/vfb/vfb.owl",
        "label":"Thing",
        "is_defining_ontology":false,
        "is_root":true,
        "olsId":"vfb:http://www.w3.org/2002/07/owl#Thing",
        "is_obsolete":false
      }
    },
    {
      "id":"1446",
      "labels":[
        "Class",
        "VFB",
        "_Class",
        "Synaptic_neuropil",
        "Synaptic_neuropil_domain",
        "Anatomy",
        "Entity"
      ],
      "properties":{
        "iri":"http://purl.obolibrary.org/obo/FBbt_00040007",
        "in_subset":[
          "cur",
          "larval_OF"
        ],
        "annotation-id":[
          "FBbt:00040007"
        ],
        "has_children":true,
        "superClassDescription":[
          "<a href=\"http://purl.obolibrary.org/obo/BFO_0000050\" class='ObjectProperty mansyntax' title=\"http://purl.obolibrary.org/obo/BFO_0000050\">part&nbsp;of</a> <span class='some'>some</span> <a href=\"http://purl.obolibrary.org/obo/FBbt_00040005\" class='mansyntax Class' title=\"http://purl.obolibrary.org/obo/FBbt_00040005\">synaptic&nbsp;neuropil</a>"
        ],
        "ontology_prefix":"VFB",
        "description":[
          "Region of synaptic neuropil whose boundaries are largely discontinuities in the density of presynaptic terminals: high density in the synaptic neuropil domain, lower or zero density outside this region. These boundaries often correspond to a boundary with glial sheath, tract neuropil or cortex."
        ],
        "annotation-has_obo_namespace":[
          "fly_anatomy.ontology"
        ],
        "label":"synaptic neuropil domain",
        "is_defining_ontology":false,
        "is_root":false,
        "is_obsolete":false,
        "ontology_name":"vfb",
        "synonym":[
          "fibrous neuropil",
          "synaptic neuropil"
        ],
        "annotation-creation_date":[
          "2009-12-09T05:03:55Z"
        ],
        "short_form":"FBbt_00040007",
        "ontology_iri":"http://purl.obolibrary.org/obo/fbbt/vfb/vfb.owl",
        "obo_id":"FBbt:00040007",
        "obo_xref":[
          "{\"database\":\"VFB\",\"id\":\"FBbt_00040007\",\"description\":null,\"url\":null}"
        ],
        "annotation-database_cross_reference":[
          "VFB:FBbt_00040007"
        ],
        "obo_definition_citation":[
          "{\"definition\":\"Region of synaptic neuropil whose boundaries are largely discontinuities in the density of presynaptic terminals: high density in the synaptic neuropil domain, lower or zero density outside this region. These boundaries often correspond to a boundary with glial sheath, tract neuropil or cortex.\",\"oboXrefs\":[{\"database\":\"FlyBase\",\"id\":\"FBrf0155900\",\"description\":null,\"url\":null},{\"database\":\"FlyBase\",\"id\":\"FBrf0224194\",\"description\":null,\"url\":null},{\"database\":null,\"id\":\"http://flybrain.neurobio.arizona.edu/Flybrain/html/terms/terms.html\",\"description\":null,\"url\":\"http://flybrain.neurobio.arizona.edu/Flybrain/html/terms/terms.html\"}]}"
        ],
        "olsId":"vfb:http://purl.obolibrary.org/obo/FBbt_00040007"
      }
    },
    {
      "id":"25175",
      "labels":[
        "Class",
        "VFB",
        "_Class",
        "Synaptic_neuropil",
        "Synaptic_neuropil_domain",
        "Anatomy",
        "Entity"
      ],
      "properties":{
        "iri":"http://purl.obolibrary.org/obo/FBbt_00003982",
        "in_subset":[
          "cur",
          "BrainName"
        ],
        "annotation-id":[
          "FBbt:00003982"
        ],
        "has_children":true,
        "superClassDescription":[
          "<a href=\"http://purl.obolibrary.org/obo/BFO_0000050\" class='ObjectProperty mansyntax' title=\"http://purl.obolibrary.org/obo/BFO_0000050\">part&nbsp;of</a> <span class='some'>some</span> <a href=\"http://purl.obolibrary.org/obo/FBbt_00045048\" class='mansyntax Class' title=\"http://purl.obolibrary.org/obo/FBbt_00045048\">saddle</a>"
        ],
        "ontology_prefix":"VFB",
        "description":[
          "Neuropil domain located in the deutocerebrum, postero-ventral to the antennal lobe. It contains the terminals of mechanosensory fibers mainly from the first and second antennal segments, most of which come from Johnston's organ neurons. This neuropil is absent from the larval brain, being formed during pupal development."
        ],
        "annotation-has_obo_namespace":[
          "fly_anatomy.ontology"
        ],
        "label":"antennal mechanosensory and motor center",
        "is_defining_ontology":false,
        "is_root":false,
        "is_obsolete":false,
        "ontology_name":"vfb",
        "synonym":[
          "antenno-mechanosensory center",
          "dorsal lobe",
          "antennal mechanosensory region",
          "AMC",
          "AMMC"
        ],
        "obo_synonym":[
          "{\"name\":\"antenno-mechanosensory center\",\"scope\":\"hasExactSynonym\",\"type\":null,\"xrefs\":[{\"database\":\"FlyBase\",\"id\":\"FBrf0187921\",\"description\":null,\"url\":null}]}",
          "{\"name\":\"dorsal lobe\",\"scope\":\"hasRelatedSynonym\",\"type\":null,\"xrefs\":[{\"database\":\"FlyBase\",\"id\":\"FBrf0239479\",\"description\":null,\"url\":null}]}",
          "{\"name\":\"AMC\",\"scope\":\"hasExactSynonym\",\"type\":null,\"xrefs\":[{\"database\":\"FlyBase\",\"id\":\"FBrf0187921\",\"description\":null,\"url\":null}]}"
        ],
        "short_form":"FBbt_00003982",
        "ontology_iri":"http://purl.obolibrary.org/obo/fbbt/vfb/vfb.owl",
        "obo_id":"FBbt:00003982",
        "obo_xref":[
          "{\"database\":\"VFB\",\"id\":\"FBbt_00003982\",\"description\":null,\"url\":null}"
        ],
        "annotation-database_cross_reference":[
          "VFB:FBbt_00003982"
        ],
        "obo_definition_citation":[
          "{\"definition\":\"Neuropil domain located in the deutocerebrum, postero-ventral to the antennal lobe. It contains the terminals of mechanosensory fibers mainly from the first and second antennal segments, most of which come from Johnston's organ neurons. This neuropil is absent from the larval brain, being formed during pupal development.\",\"oboXrefs\":[{\"database\":null,\"id\":\"http://flybrain.neurobio.arizona.edu/Flybrain/html/terms/terms.html\",\"description\":null,\"url\":\"http://flybrain.neurobio.arizona.edu/Flybrain/html/terms/terms.html\"},{\"database\":\"FlyBase\",\"id\":\"FBrf0194812\",\"description\":null,\"url\":null},{\"database\":\"VFB_vol\",\"id\":\"00003982\",\"description\":null,\"url\":null},{\"database\":\"FlyBase\",\"id\":\"FBrf0211016\",\"description\":null,\"url\":null}]}"
        ],
        "olsId":"vfb:http://purl.obolibrary.org/obo/FBbt_00003982"
      }
    },
    {
      "id":"282",
      "labels":[
        "Class",
        "VFB",
        "_Class",
        "Anatomy",
        "Entity"
      ],
      "properties":{
        "iri":"http://purl.obolibrary.org/obo/FBbt_00007016",
        "in_subset":[
          "cur",
          "larval_OF"
        ],
        "annotation-id":[
          "FBbt:00007016"
        ],
        "has_children":true,
        "ontology_prefix":"VFB",
        "annotation-has_obo_namespace":[
          "fly_anatomy.ontology"
        ],
        "label":"material anatomical entity",
        "is_defining_ontology":false,
        "is_root":false,
        "is_obsolete":false,
        "ontology_name":"vfb",
        "short_form":"FBbt_00007016",
        "ontology_iri":"http://purl.obolibrary.org/obo/fbbt/vfb/vfb.owl",
        "obo_id":"FBbt:00007016",
        "obo_xref":[
          "{\"database\":\"CARO\",\"id\":\"0000006\",\"description\":null,\"url\":null}"
        ],
        "annotation-database_cross_reference":[
          "CARO:0000006"
        ],
        "olsId":"vfb:http://purl.obolibrary.org/obo/FBbt_00007016"
      }
    },
    {
      "id":"7754",
      "labels":[
        "Class",
        "VFB",
        "_Class",
        "Anatomy",
        "Entity"
      ],
      "properties":{
        "iri":"http://purl.obolibrary.org/obo/FBbt_10000000",
        "in_subset":[
          "cur",
          "EmbDevSlim",
          "larval_OF"
        ],
        "annotation-id":[
          "FBbt:10000000"
        ],
        "has_children":true,
        "ontology_prefix":"VFB",
        "description":[
          "Anatomical entity which is part_of Drosophila melanogaster."
        ],
        "annotation-has_obo_namespace":[
          "fly_anatomy.ontology"
        ],
        "label":"anatomical entity",
        "is_defining_ontology":false,
        "is_root":true,
        "annotation-has_alternative_id":[
          "FBbt_root:00000000"
        ],
        "is_obsolete":false,
        "ontology_name":"vfb",
        "synonym":[
          "Drosophila"
        ],
        "short_form":"FBbt_10000000",
        "ontology_iri":"http://purl.obolibrary.org/obo/fbbt/vfb/vfb.owl",
        "obo_id":"FBbt:10000000",
        "obo_definition_citation":[
          "{\"definition\":\"Anatomical entity which is part_of Drosophila melanogaster.\",\"oboXrefs\":[{\"database\":\"CARO\",\"id\":\"MAH\",\"description\":null,\"url\":null}]}"
        ],
        "olsId":"vfb:http://purl.obolibrary.org/obo/FBbt_10000000"
      }
    },
    {
      "id":"7709",
      "labels":[
        "Class",
        "VFB",
        "_Class",
        "Anatomy",
        "Entity"
      ],
      "properties":{
        "iri":"http://purl.obolibrary.org/obo/FBbt_00007001",
        "in_subset":[
          "cur",
          "larval_OF"
        ],
        "annotation-id":[
          "FBbt:00007001"
        ],
        "has_children":true,
        "ontology_prefix":"VFB",
        "description":[
          "Material anatomical entity that has inherent 3D shape, whose parts are all connected and that is generated by coordinated expression of the organism's own genome."
        ],
        "annotation-has_obo_namespace":[
          "fly_anatomy.ontology"
        ],
        "label":"anatomical structure",
        "is_defining_ontology":false,
        "is_root":false,
        "is_obsolete":false,
        "ontology_name":"vfb",
        "short_form":"FBbt_00007001",
        "ontology_iri":"http://purl.obolibrary.org/obo/fbbt/vfb/vfb.owl",
        "obo_id":"FBbt:00007001",
        "obo_xref":[
          "{\"database\":\"CARO\",\"id\":\"0000003\",\"description\":null,\"url\":null}"
        ],
        "annotation-database_cross_reference":[
          "CARO:0000003"
        ],
        "obo_definition_citation":[
          "{\"definition\":\"Material anatomical entity that has inherent 3D shape, whose parts are all connected and that is generated by coordinated expression of the organism's own genome.\",\"oboXrefs\":[{\"database\":\"CARO\",\"id\":\"MAH\",\"description\":null,\"url\":null},{\"database\":\"FBC\",\"id\":\"DOS\",\"description\":null,\"url\":null}]}"
        ],
        "olsId":"vfb:http://purl.obolibrary.org/obo/FBbt_00007001"
      }
    },
    {
      "id":"15463",
      "labels":[
        "Class",
        "VFB",
        "_Class",
        "Synaptic_neuropil",
        "Anatomy",
        "Entity"
      ],
      "properties":{
        "iri":"http://purl.obolibrary.org/obo/FBbt_00040005",
        "annotation-id":[
          "FBbt:00040005"
        ],
        "has_children":true,
        "superClassDescription":[
          "<a href=\"http://purl.obolibrary.org/obo/BFO_0000050\" class='ObjectProperty mansyntax' title=\"http://purl.obolibrary.org/obo/BFO_0000050\">part&nbsp;of</a> <span class='some'>some</span> <a href=\"http://purl.obolibrary.org/obo/FBbt_00005139\" class='mansyntax Class' title=\"http://purl.obolibrary.org/obo/FBbt_00005139\">neuropil</a>"
        ],
        "ontology_prefix":"VFB",
        "description":[
          "The part of the neuropil consisting largely of synapsing neuron projections."
        ],
        "annotation-has_obo_namespace":[
          "fly_anatomy.ontology"
        ],
        "label":"synaptic neuropil",
        "is_defining_ontology":false,
        "is_root":false,
        "is_obsolete":false,
        "ontology_name":"vfb",
        "annotation-creation_date":[
          "2009-08-12T06:32:24Z"
        ],
        "short_form":"FBbt_00040005",
        "ontology_iri":"http://purl.obolibrary.org/obo/fbbt/vfb/vfb.owl",
        "obo_id":"FBbt:00040005",
        "obo_xref":[
          "{\"database\":\"VFB\",\"id\":\"FBbt_00040005\",\"description\":null,\"url\":null}"
        ],
        "annotation-database_cross_reference":[
          "VFB:FBbt_00040005"
        ],
        "obo_definition_citation":[
          "{\"definition\":\"The part of the neuropil consisting largely of synapsing neuron projections.\",\"oboXrefs\":[{\"database\":\"FlyBase\",\"id\":\"FBrf0224194\",\"description\":null,\"url\":null}]}"
        ],
        "olsId":"vfb:http://purl.obolibrary.org/obo/FBbt_00040005",
        "annotation-created_by":[
          "djs93"
        ]
      }
    }
  ],
  "links":[
    {
      "id":"9953",
      "type":"SUBCLASSOF",
      "source":"2962",
      "target":"7709",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"107154",
      "type":"SUBCLASSOF",
      "source":"25175",
      "target":"1446",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"9592",
      "type":"SUBCLASSOF",
      "source":"282",
      "target":"7754",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"131262",
      "type":"SUBCLASSOF",
      "source":"7754",
      "target":"148",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"9550",
      "type":"SUBCLASSOF",
      "source":"7709",
      "target":"282",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"20303",
      "type":"SUBCLASSOF",
      "source":"1446",
      "target":"2962",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"107154",
      "type":"SUBCLASSOF",
      "source":"25175",
      "target":"1446",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"20302",
      "type":"SUBCLASSOF",
      "source":"1446",
      "target":"15463",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"107154",
      "type":"SUBCLASSOF",
      "source":"25175",
      "target":"1446",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"20267",
      "type":"SUBCLASSOF",
      "source":"15463",
      "target":"282",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"20302",
      "type":"SUBCLASSOF",
      "source":"1446",
      "target":"15463",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"107154",
      "type":"SUBCLASSOF",
      "source":"25175",
      "target":"1446",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"9592",
      "type":"SUBCLASSOF",
      "source":"282",
      "target":"7754",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"20267",
      "type":"SUBCLASSOF",
      "source":"15463",
      "target":"282",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"20302",
      "type":"SUBCLASSOF",
      "source":"1446",
      "target":"15463",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"107154",
      "type":"SUBCLASSOF",
      "source":"25175",
      "target":"1446",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"9592",
      "type":"SUBCLASSOF",
      "source":"282",
      "target":"7754",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"20267",
      "type":"SUBCLASSOF",
      "source":"15463",
      "target":"282",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"131262",
      "type":"SUBCLASSOF",
      "source":"7754",
      "target":"148",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    },
    {
      "id":"20302",
      "type":"SUBCLASSOF",
      "source":"1446",
      "target":"15463",
      "properties":{
        "iri":"http://www.w3.org/2000/01/rdf-schema#subClassOf",
        "ontology_name":"vfb",
        "__type__":"SubClassOf",
        "label":"is a",
        "uri":"http://www.w3.org/2000/01/rdf-schema#subClassOf"
      }
    }
  ]
};


module.exports = { graph };
