name: Process XMI and Update README in /model

on:
  push:
    paths:
      - 'model/*.xmi'
      - '.github/workflows/process_xmi.yml'
      - '.github/scripts/process_xmi.py'
      - '.github/scripts/extractqueries.py'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml  # Add other dependencies as necessary

    - name: Process XMI File and Update README
      run: |
        python ./.github/scripts/process_xmi.py ./model/vfb.xmi ./model/README.md
    - name: Process XMI File and Update query
      run: |
        python ./.github/scripts/extractqueries.py ./model/vfb.xmi ./model/query.md


    - name: Commit README.md
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add model/*.md
        git commit -m "Update README with XMI structure and query breakdowns" || echo "No changes to commit"
        git push
